package com.chenglulu.constant;

public interface ErrorCode {
    String UNKNOWN_ERROR="UNKNOWN_ERROR";
    String SUCCESS="SUCCESS";
    String PARAMETER_ERROR="PARAMETER_ERROR";

    String LOGIN_ERROR="LOGIN_ERROR";

    // Authorization不存在或者格式不正确
    String AUTHORIZATION_INVALID="AUTHORIZATION_INVALID";
    String AUTHORIZATION_TOKEN_EXPIRED="AUTHORIZATION_TOKEN_EXPIRED";
    String AUTHORIZATION_PARSE_TOKEN_ERROR="AUTHORIZATION_PARSE_TOKEN_ERROR";

    //user
    String USER_NOT_LOGIN="USER_NOT_LOGIN";
    String USER_NOT_EXIST="USER_NOT_EXIST";
    String USER_EMAIL_EXIST="USER_EMAIL_EXIST";
    String USER_PHONE_EXIST="USER_PHONE_EXIST";
    String USER_ROLE_NOT_EXIST="USER_ROLE_NOT_EXIST";
    String USER_CREATE_ROLE_CAN_NOT_SUPER="USER_CREATE_ROLE_CAN_NOT_SUPER";

    // roles
    String ROLES_EXIST="ROLES_EXIST";
}
